services:
  ib-gateway:
    image: manhinhang/ib-gateway-docker
    command: tail -f /dev/null
    ports:
      - 4002:4002
    environment:
      - IB_ACCOUNT=$IB_ACCOUNT
      - IB_PASSWORD=$IB_PASSWORD
      - TRADING_MODE=$TRADING_MODE
secrets:
  IB_ACCOUNT:
    environment: "IB_ACCOUNT"
  IB_PASSWORD:
    environment: "IB_PWD"
  TRADING_MODE:
    environment: "TRADING_MODE"
