services:
  ib-gateway:
    build:
      context: .
    ports:
      - 4002:4002
    environment:
      - IB_ACCOUNT=$IB_ACCOUNT
      - IB_PASSWORD=$IB_PASSWORD
      - TRADING_MODE=$TRADING_MODE
    healthcheck:
        test: /healthcheck/bin/healthcheck
        interval: 60s
        timeout: 30s
        retries: 3
        start_period: 60s

