apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  password: {{ .Values.secret.password | b64enc }}
  username: {{ .Values.secret.username | b64enc }}
  trading_mode: {{ .Values.secret.trading_mode | b64enc }}