/*
 * This source file was generated by the Gradle 'init' task
 */
package com.manhinhang.ibgatewaydocker.healthcheck
import kotlinx.coroutines.*

fun main() = runBlocking {
    val client = IBGatewayClient()
    val result = client.ping()
    result.exceptionOrNull()?.let { throw it }
    return@runBlocking
}