/*
 * This source file was generated by the Gradle 'init' task
 */
package com.manhinhang.ibgatewaydocker.healthcheck
import com.ib.client.*;
import kotlin.system.exitProcess

fun main() {

    val clientId = (System.getenv("HEALTHCHECK_CLIENT_ID")?.toIntOrNull() ?: 999)
    val port = (System.getenv("IB_GATEWAY_INTERNAL_PORT")?.toIntOrNull() ?: 4001)
    val signal = EJavaSignal();
    val client = EClientSocket(Wrapper(), signal)
    client.eConnect("localhost", port, clientId)
    val reader = EReader(client, signal)
    reader.start()
    Thread {
        while (client.isConnected) {
            client.eDisconnect()
            println("Ping IB Gateway successful")
            exitProcess(0)
        }
        println("Can not connect to IB Gateway")
        exitProcess(1)
    }.start()
}
