/*
 * This source file was generated by the Gradle 'init' task
 */
package com.manhinhang.ibgatewaydocker.heathcheck
import com.ib.client.*;
import kotlin.system.exitProcess

fun main() {

    val clientId = 999
    val port = 4002
    val signal = EJavaSignal();
    val client = EClientSocket(Wrapper(), signal)
    client.eConnect("localhost", port, clientId)
    val reader = EReader(client, signal)
    reader.start()
    Thread {
        while (client.isConnected) {
            exitProcess(0)
        }
        exitProcess(-1)
    }.start()
}
