/*
 * This source file was generated by the Gradle 'init' task
 */
package com.manhinhang.ibgatewaydocker.healthcheck

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {

    }
}
