name: "Publish Docker"

on:
   push:
     branches:
        - '*' 
        - '!feature/**' 
        - '!hotfix/**'
        - '!bugfix/**' 
     tags:
       - '*'
   workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          # Dockerhub
          - images: manhinhang/ib-gateway-docker
            username: DOCKERHUB_USERNAME
            password: DOCKERHUB_PASSWORD
            registry: ''
          # Github
          - images: ghcr.io/manhinhang/ib-gateway-docker
            username: ${{ github.actor }}
            password: GITHUB_TOKEN
            registry: 'ghcr.io'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@master
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.images }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ matrix.registry }}
          username: ${{ matrix.registry == 'ghcr.io' && matrix.username || secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  chart-release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: helm
