package com.manhinhang.ibgatewaydocker.healthcheck

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * Verifies that the generated Wrapper records IB gateway errors via the
 * three error() overloads. Wrapper.kt is regenerated by
 * generate-wrapper.sh before this test runs.
 */
class WrapperTest {

    @Test
    fun `error with Exception captures the message`() {
        val wrapper = Wrapper()
        wrapper.error(RuntimeException("boom"))
        assertEquals("boom", wrapper.lastError)
    }

    @Test
    fun `error with Exception falls back to toString when message is null`() {
        val wrapper = Wrapper()
        wrapper.error(RuntimeException())
        assertTrue(wrapper.lastError?.contains("RuntimeException") == true)
    }

    @Test
    fun `error with String captures the string`() {
        val wrapper = Wrapper()
        wrapper.error("connection lost")
        assertEquals("connection lost", wrapper.lastError)
    }

    @Test
    fun `error with code and message captures both`() {
        val wrapper = Wrapper()
        wrapper.error(1, 0L, 502, "Couldn't connect to TWS", null)
        assertEquals("[502] Couldn't connect to TWS", wrapper.lastError)
    }

    @Test
    fun `informational codes do not update lastError`() {
        val wrapper = Wrapper()
        Wrapper.INFORMATIONAL_ERROR_CODES.forEach { code ->
            wrapper.lastError = null
            wrapper.error(1, 0L, code, "Market data farm connection is OK", null)
            assertNull(
                wrapper.lastError,
                "Code $code should be filtered as informational",
            )
        }
    }

    @Test
    fun `lastError can be reset between checks`() {
        val wrapper = Wrapper()
        wrapper.error("first")
        assertEquals("first", wrapper.lastError)
        wrapper.lastError = null
        assertNull(wrapper.lastError)
    }
}
